import {
  Environment,
  ServiceRequest,
  BOM,
  BOMItem,
  Template,
  Integration,
  User,
} from "@/types"

export const currentUser: User = {
  id: "user-1",
  name: "Rajesh Kumar",
  email: "rajesh.kumar@marutisuzuki.com",
  role: "Developer",
  mslId: "MSL12345",
}

export const mockEnvironments: Environment[] = [
  {
    id: "env-1",
    name: "Project Alpha - Development",
    project: "Project Alpha",
    type: "dev",
    status: "active",
    resources: 12,
    cost: 485.67,
    health: 98,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-12-26T08:30:00Z",
    serviceRequests: ["sr-1", "sr-2", "sr-3"],
  },
  {
    id: "env-2",
    name: "Project Beta - QA",
    project: "Project Beta",
    type: "qa",
    status: "provisioning",
    resources: 8,
    cost: 320.45,
    health: 85,
    createdAt: "2025-12-20T14:00:00Z",
    updatedAt: "2025-12-26T09:15:00Z",
    serviceRequests: ["sr-4", "sr-5"],
  },
  {
    id: "env-3",
    name: "Project Gamma - Production",
    project: "Project Gamma",
    type: "prod",
    status: "active",
    resources: 24,
    cost: 1250.89,
    health: 99,
    createdAt: "2024-11-10T09:00:00Z",
    updatedAt: "2025-12-26T07:45:00Z",
    serviceRequests: [],
  },
  {
    id: "env-4",
    name: "Project Delta - UAT",
    project: "Project Delta",
    type: "uat",
    status: "partial",
    resources: 10,
    cost: 425.30,
    health: 75,
    createdAt: "2025-12-18T11:00:00Z",
    updatedAt: "2025-12-26T06:20:00Z",
    serviceRequests: ["sr-6"],
  },
]

export const mockServiceRequests: ServiceRequest[] = [
  {
    id: "sr-1",
    type: "infrastructure",
    title: "Provision ECS Cluster for Microservices",
    description: "Create ECS cluster with m6g.large instances for microservices deployment",
    environment: "env-1",
    environmentType: "dev",
    status: "completed",
    priority: "high",
    confidence: 95,
    createdBy: currentUser.id,
    createdAt: "2025-01-15T10:30:00Z",
    updatedAt: "2025-01-18T16:45:00Z",
    approvalChain: [
      {
        approver: "Manager Name",
        role: "Manager",
        status: "approved",
        timestamp: "2025-01-15T14:00:00Z",
      },
      {
        approver: "IT Manager Name",
        role: "IT Manager",
        status: "approved",
        timestamp: "2025-01-16T10:00:00Z",
      },
    ],
    details: {
      instanceType: "m6g.large",
      count: 2,
      storage: "100GB",
    },
    notes: ["Approved for immediate provisioning"],
  },
  {
    id: "sr-2",
    type: "firewall",
    title: "Firewall Rule for Payment Gateway Integration",
    description: "Allow outbound traffic to payment gateway on port 443",
    environment: "env-1",
    environmentType: "dev",
    status: "approved",
    priority: "high",
    confidence: 92,
    createdBy: currentUser.id,
    createdAt: "2025-02-01T09:00:00Z",
    updatedAt: "2025-02-03T11:30:00Z",
    approvalChain: [
      {
        approver: "Security Team",
        role: "Security Manager",
        status: "approved",
        timestamp: "2025-02-03T11:30:00Z",
      },
    ],
    details: {
      sourceSubnet: "10.0.1.0/24",
      destinationIP: "203.45.67.89",
      port: 443,
      protocol: "TCP",
    },
    notes: [],
    pendingOn: "Network Team",
  },
  {
    id: "sr-3",
    type: "access",
    title: "Developer Access to Production Database",
    description: "Read-only access for debugging production issues",
    environment: "env-1",
    environmentType: "dev",
    status: "pending",
    priority: "medium",
    confidence: 88,
    createdBy: currentUser.id,
    createdAt: "2025-12-24T14:00:00Z",
    updatedAt: "2025-12-24T14:00:00Z",
    approvalChain: [
      {
        approver: "Manager Name",
        role: "Manager",
        status: "pending",
      },
    ],
    details: {
      database: "prod-customer-db",
      accessType: "read-only",
      duration: "24 hours",
    },
    notes: [],
    pendingOn: "Manager",
  },
  {
    id: "sr-4",
    type: "network",
    title: "NAT Gateway Configuration",
    description: "Configure NAT gateway for private subnet internet access",
    environment: "env-2",
    environmentType: "qa",
    status: "in_progress",
    priority: "high",
    confidence: 96,
    createdBy: currentUser.id,
    createdAt: "2025-12-20T14:30:00Z",
    updatedAt: "2025-12-26T08:00:00Z",
    approvalChain: [
      {
        approver: "IT Manager",
        role: "IT Manager",
        status: "approved",
        timestamp: "2025-12-21T10:00:00Z",
      },
    ],
    details: {
      subnet: "10.0.2.0/24",
      availabilityZone: "ap-south-1a",
    },
    notes: ["Provisioning in progress"],
    pendingOn: "Execution Team",
  },
]

export const mockBOMItems: BOMItem[] = [
  {
    service: "Prifunl VPN",
    serviceType: "Amazon EC2",
    resourceName: "VPN Server",
    region: "Asia Pacific Mumbai",
    configuration: "t3a.micro | 1Core, 2GB Mem | 50GB",
    estimatedCost: 9.09,
  },
  {
    service: "Jenkins",
    serviceType: "Amazon EC2",
    resourceName: "Jenkins CI/CD",
    region: "Asia Pacific Mumbai",
    configuration: "t4g.medium | 2Core, 4GB Mem | 100GB",
    estimatedCost: 27.08,
  },
  {
    service: "Terraform",
    serviceType: "Amazon EC2",
    resourceName: "Infrastructure as Code",
    region: "Asia Pacific Mumbai",
    configuration: "t4g.small | 2Core, 2GB Mem | 50GB",
    estimatedCost: 12.74,
  },
  {
    service: "ELK",
    serviceType: "Amazon EC2",
    resourceName: "Logging & Monitoring",
    region: "Asia Pacific Mumbai",
    configuration: "t4g.medium | 2Core, 4GB Mem | 100GB",
    estimatedCost: 22.52,
  },
  {
    service: "Airflow",
    serviceType: "Amazon EC2",
    resourceName: "Workflow Orchestration",
    region: "Asia Pacific Mumbai",
    configuration: "t4g.medium | 2Core, 4GB Mem | 50GB",
    estimatedCost: 17.96,
  },
  {
    service: "Application Server",
    serviceType: "Amazon ECS",
    resourceName: "ECS Compute",
    region: "Asia Pacific Mumbai",
    configuration: "m6g.large (spot) | 4Core, 16GB Mem",
    estimatedCost: 50.6,
  },
  {
    service: "Database",
    serviceType: "Amazon RDS",
    resourceName: "PostgreSQL",
    region: "Asia Pacific Mumbai",
    configuration: "db.t4g.medium | Multi-AZ",
    estimatedCost: 80.15,
  },
  {
    service: "NAT Gateway",
    serviceType: "Amazon VPC",
    resourceName: "NAT Gateway",
    region: "Asia Pacific Mumbai",
    configuration: "Standard",
    estimatedCost: 46.0,
  },
  {
    service: "Route 53",
    serviceType: "Amazon Route 53",
    resourceName: "DNS Hosting",
    region: "Global",
    configuration: "Hosted Zone",
    estimatedCost: 0.5,
  },
  {
    service: "Application Load Balancer",
    serviceType: "Amazon ELB",
    resourceName: "Load Balancer",
    region: "Asia Pacific Mumbai",
    configuration: "Application LB",
    estimatedCost: 23.29,
  },
  {
    service: "S3",
    serviceType: "Amazon S3",
    resourceName: "Object Storage",
    region: "Asia Pacific Mumbai",
    configuration: "Standard Storage",
    estimatedCost: 2.0,
  },
]

export const mockBOM: BOM = {
  id: "bom-1",
  projectName: "Project Alpha",
  environmentType: "dev",
  items: mockBOMItems,
  totalCost: mockBOMItems.reduce((sum, item) => sum + item.estimatedCost, 0),
  createdAt: "2025-01-15T10:00:00Z",
  category: "infrastructure",
}

export const mockTemplates: Template[] = [
  {
    id: "template-1",
    name: "Recommended - Full Stack Web Application",
    description: "Complete infrastructure for full-stack web applications with microservices architecture",
    matchPercentage: 95,
    coverage: 98,
    costEstimate: 485.67,
    compliant: true,
    items: mockBOMItems,
  },
  {
    id: "template-2",
    name: "Cost-Optimized - Basic Web Application",
    description: "Cost-optimized infrastructure for basic web applications",
    matchPercentage: 88,
    coverage: 85,
    costEstimate: 320.45,
    compliant: true,
    items: mockBOMItems.slice(0, 8),
  },
  {
    id: "template-3",
    name: "Basic - Minimal Infrastructure",
    description: "Minimal infrastructure for simple applications",
    matchPercentage: 82,
    coverage: 75,
    costEstimate: 245.30,
    compliant: true,
    items: mockBOMItems.slice(0, 6),
  },
]

export const mockIntegrations: Integration[] = [
  {
    id: "int-1",
    name: "Payment Gateway - Razorpay",
    type: "Payment",
    endpoint: "https://api.razorpay.com",
    port: 443,
    authMethod: "API Key",
    sla: "99.9% uptime",
    documentation: "https://razorpay.com/docs/api",
  },
  {
    id: "int-2",
    name: "SMS Provider - Twilio",
    type: "Messaging",
    endpoint: "https://api.twilio.com",
    port: 443,
    authMethod: "OAuth 2.0",
    sla: "99.95% uptime",
    documentation: "https://www.twilio.com/docs",
  },
  {
    id: "int-3",
    name: "Email Service - SendGrid",
    type: "Email",
    endpoint: "https://api.sendgrid.com",
    port: 443,
    authMethod: "API Key",
    sla: "99.9% uptime",
    documentation: "https://sendgrid.com/docs",
  },
  {
    id: "int-4",
    name: "CRM - Salesforce",
    type: "CRM",
    endpoint: "https://api.salesforce.com",
    port: 443,
    authMethod: "OAuth 2.0",
    sla: "99.9% uptime",
    documentation: "https://developer.salesforce.com/docs",
  },
]
